parameters:
    anyx.login_gate.authentication.listener.form.class: Anyx\LoginGateBundle\Security\UsernamePasswordFormAuthenticationListener
services:
    anyx.login_gate.storage.session:
        class: Anyx\LoginGateBundle\Storage\SessionStorage
    anyx.login_gate.attempt_storage:
        class: Anyx\LoginGateBundle\Storage\CompositeStorage
    anyx.login_gate.brute_force_checker:
        class: Anyx\LoginGateBundle\Service\BruteForceChecker
        arguments: ['@anyx.login_gate.attempt_storage', '%anyx.login_gate.brute_force_checker_options%']
    anyx.login_gate.autentication_handler:
        class: Anyx\LoginGateBundle\Security\AuthenticationHandler
        arguments: ['@request_stack', '@anyx.login_gate.attempt_storage', '%anyx.login_gate.method%' ]
        tags:
            - { name: kernel.event_subscriber }
